# 带 process_reward
export CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
export HF_ENDPOINT="https://hf-mirror.com"
export PP_ENDPOINT="https://pypi.tuna.tsinghua.edu.cn/simple"
export EXPERIMENT_NAME="Qwen3-8B"
export TIME="xxx"
export WANDB_BASE_URL="https://api.bandw.top"
export WANDB_API_KEY="xxx"
export HYDRA_FULL_ERROR=1

export BASE_MODEL='/private/model' # Qwen3-8B
WAND_PROJECT="$EXPERIMENT_NAME-$TIME"
PROJECT_DIR="/private/xxx"
export DATA_DIR="$PROJECT_DIR/data/xxx"
TRAIN_DATA="$DATA_DIR/train.parquet"
TEST_DATA="$DATA_DIR/test.parquet"
DEFAULT_LOCAL_DIR="$PROJECT_DIR/MSR/$EXPERIMENT_NAME/$TIME"
REWARD_PATH="$PROJECT_DIR/my_reward/reward.py"
TOOL_CONFIG_PATH="$PROJECT_DIR/examples/sglang_multiturn/config/tool_config/gsm8k_tool_config.yaml"

python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_batch_size=256 \
    data.val_batch_size=32 \
    data.max_prompt_length=16384 \
    data.max_response_length=8192 \
    data.max_start_length=8192 \
    data.max_obs_length=8192 \
    max_turns=8 \
    data.return_raw_chat=True \
    +data.enable_thinking=False \
    actor_rollout_ref.model.path=$BASE_MODEL \
    actor_rollout_ref.model.use_fused_kernels=True \
    actor_rollout_ref.model.lora_rank=0 \
    actor_rollout_ref.model.lora_alpha=32 \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.entropy_coeff=0 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.actor.use_kl_loss=False \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=True \
    actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=16 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.max_num_seqs=128 \
    actor_rollout_ref.rollout.max_num_batched_tokens=131072 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.8 \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.ref.fsdp_config.param_offload=False \
    algorithm.use_kl_in_reward=True \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    trainer.val_before_train=true \
    trainer.project_name=$WAND_PROJECT \
    trainer.experiment_name=$EXPERIMENT_NAME \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=20 \
    trainer.test_freq=20 \
    trainer.default_local_dir=$DEFAULT_LOCAL_DIR \
    data.train_files=$TRAIN_DATA \
    data.val_files=$TEST_DATA \
    ray_init.num_cpus=32 \
    custom_reward_function.path=$REWARD_PATH \
    actor_rollout_ref.rollout.multi_turn.tool_config_path=$TOOL_CONFIG_PATH \
    trainer.total_epochs=15 \
    trainer.total_training_steps=1005 \
    2>&1 | tee "$EXPERIMENT_NAME.log"